path requirements
Signed-off-by: com-wuqi <wuqi9277@outlook.com>

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -30,16 +30,13 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
-      #      - name: Run quick tests before build
-      #        env:
-      #          DRIVER: "~aiohttp"
-      #        run: |
-      #          python -m pip install --upgrade pip
-      #          pip install -r requirements.txt
-      #          if [ -f requirements-test.txt ]; then
-      #            pip install -r requirements-test.txt
-      #          fi
-      #          python -m pytest tests/ -v --tb=short --disable-warnings || echo "Tests failed, but continuing with build (check separate test workflow for details)"
+      - name: Run quick tests before build
+        env:
+          DRIVER: "~aiohttp"
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+          python -m pytest tests/ -v --tb=short --disable-warnings || echo "Tests failed, but continuing with build (check separate test workflow for details)"
 
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v4
